/*Generated by WaveMaker Studio*/

package com.mobile_localization.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.mobile_localization.hrdb.models.query.*;

public interface HrdbQueryExecutorService {

    Page<HrdbUserDataResponse> executeHrdbUserData(Pageable pageable);

    Downloadable exportHrdbUserData(ExportType exportType, Pageable pageable);

}


